//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebalanceModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RebalanceModel()
        {
            this.TemplateDetailsItemParameters = new HashSet<TemplateDetailsItemParameter>();
            this.TemplateDetailsItemParameters1 = new HashSet<TemplateDetailsItemParameter>();
        }
    
        public string ModelId { get; set; }
        public string ModelName { get; set; }
        public string Adviser_AdviserId { get; set; }
        public int ProfileId { get; set; }
        public string ClientGroup_ClientGroupId { get; set; }
    
        public virtual Adviser Adviser { get; set; }
        public virtual ClientGroup ClientGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDetailsItemParameter> TemplateDetailsItemParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDetailsItemParameter> TemplateDetailsItemParameters1 { get; set; }
    }
}
