//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskProfile
    {
        public string RiskProfileID { get; set; }
        public string ClientID { get; set; }
        public string CapitalLossAttitude { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IncomeSource { get; set; }
        public string InvestmentKnowledge { get; set; }
        public string InvestmentObjective1 { get; set; }
        public string InvestmentObjective2 { get; set; }
        public string InvestmentObjective3 { get; set; }
        public string InvestmentProfile { get; set; }
        public Nullable<int> InvestmentTimeHorizon { get; set; }
        public string LongTermGoal1 { get; set; }
        public string LongTermGoal2 { get; set; }
        public string LongTermGoal3 { get; set; }
        public string MedTermGoal1 { get; set; }
        public string MedTermGoal2 { get; set; }
        public string MedTermGoal3 { get; set; }
        public Nullable<int> RetirementAge { get; set; }
        public Nullable<double> RetirementIncome { get; set; }
        public string RiskAttitude { get; set; }
        public Nullable<double> ShortTermAssetPercent { get; set; }
        public Nullable<double> ShortTermEquityPercent { get; set; }
        public string ShortTermGoal1 { get; set; }
        public string ShortTermGoal2 { get; set; }
        public string ShortTermGoal3 { get; set; }
        public string ShortTermTrading { get; set; }
        public int riskLevel { get; set; }
    }
}
