//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDISAngular.Infrastructure.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDetailsItemParameter
    {
        public string Id { get; set; }
        public string EquityId { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> MarketValue { get; set; }
        public Nullable<double> CurrentValue { get; set; }
        public Nullable<double> CurrentWeighting { get; set; }
        public string Model_ModelId { get; set; }
        public string identityMetaKey { get; set; }
    
        public virtual RebalanceModel RebalanceModel { get; set; }
        public virtual RebalanceModel RebalanceModel1 { get; set; }
    }
}
